### PR TITLE
Add commentary on leaderboard changes with GPT-4 

### PR DESCRIPTION
**Pull request by Lundeful**
Here is a suggestion for adding commentary on changes using GPT

Testing with a hook to my private slack DMs indicates it works fine. Prompt adjustments can be made, but this is an okay starting point.

### CODE REVIEW

**Comment by fowlie** [comment]
Very cool, thanks for contributing 🙌 I'll try to apply the change on our server and run a test.

**Comment by fowlie** [comment]
Now that we have tested a first run, the prompt response was almost correct, but it seemed to ignore the points and only look at the stars. Maybe its possible to adjust the prompt string to fix this?

For instance, in leaderboard.json, it should look at "local_score" (ignore "global_score"), which is the first number in the colon-separated files "stats" and "stats.old".

**Comment by Lundeful** [comment]
Yeah the prompt will probably need some work. I don't know if keeping the prompt in the code hardcoded like this is best or if it should be something more dynamic so it's easier to change on the spot without having to merge into main and do a redeploy. Having it like an environment variable could possibly work.

**Comment by fowlie** [comment]
This is fine. Its working so I'm merging this. We can always fine tune later.

**Pull request merged**
